import os
import ycm_core

BASE_FLAGS = [
        '-x',
        'c++',
        '-Wall',
        '-Wextra',
        '-Wshadow',
        '--pedantic',
        '-fopenmp',
        '-ferror-limit=10000',
        '-std=c++11',
        '-isystem','/home/luca/.vim/bundle/YouCompleteMe/third_party/ycmd/clang_includes/include',
        '-isystem','/home/luca/workdir/compilers/gcc/gcc-8.2.0-install/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/', # for omp.h
        '-isystem','/home/luca/workdir/compilers/openmpi/openmpi-3.1.3-install/include', # for mpi.h
        '-isystem','/home/luca/.vim',
        '-isystem','/home/luca/workdir/libs/boost/boost-install/include',
]

E3SM_FLAGS = [
        '-DHAVE_CONFIG_H',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx/mpi',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx/utilities',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx/vector',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/theta-l_kokkos/cxx',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/preqx_kokkos/cxx',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/test/unit_tests/catch2/include',
        '-I/home/luca/workdir/e3sm/e3sm-build/gcc/opt/branch/',
        '-I/home/luca/workdir/e3sm/e3sm-src/branch/cime/src/share/timing',
        '-DPLEV=72',
        '-DNP=4',
        '-DQSIZE_D=4',
]

SCREAM_FLAGS = [
        '-DHAVE_CONFIG_H',
        '-DHOMMEXX_CONFIG_IS_CMAKE',
        '-DSCREAM_CONFIG_IS_CMAKE',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/control/',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/share/',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/share/field',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/share/mpi',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/physics/p3/',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/physics/rrtmgp/',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/src/physics/shoc/',
        '-I/home/luca/workdir/scream/scream-src/branch/components/scream/extern/catch2/include',
        '-I/home/luca/workdir/scream/scream-build/gcc/debug/branch/src',
        '-I/home/luca/workdir/scream/scream-build/gcc/debug/branch/src/dynamics/homme/homme/src/share/cxx',
        '-I/home/luca/workdir/scream/scream-build/gcc/debug/branch/tests/preqx-nlev72',
        '-isystem','/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx',
        '-isystem','/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx/mpi',
        '-isystem','/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx/utilities',
        '-isystem','/home/luca/workdir/e3sm/e3sm-src/branch/components/homme/src/share/cxx/vector',
]

HOMME_FLAGS = [
        '-DHAVE_CONFIG_H',
        '-I/home/luca/workdir/hommexx/hommexx-src/components/homme/src/',
        '-I/home/luca/workdir/hommexx/hommexx-src/components/homme/src/share/cxx/',
        '-I/home/luca/workdir/hommexx/hommexx-src/components/homme/src/share/cxx/mpi',
        '-I/home/luca/workdir/hommexx/hommexx-src/components/homme/src/share/cxx/vector',
        '-I/home/luca/workdir/hommexx/hommexx-src/components/homme/test/unit_tests/',
        '-I/home/luca/workdir/hommexx/hommexx-build-debug/src/',
        '-I/home/luca/workdir/hommexx/hommexx-build-debug/test_execs/preqx_flat_ut/',
        '-I/home/luca/workdir/hommexx/hommexx-build-debug/test_execs/prtcA_flat/',
        '-I/home/luca/workdir/hommexx/hommexx-build-debug/test_execs/prtcA_flat_c/',
]

KOKKOS_FLAGS = [
        '-I/home/luca/workdir/kokkos/kokkos-src/core/src',
        '-I/home/luca/workdir/kokkos/kokkos-src/core/src/Cuda',
        '-I/home/luca/workdir/kokkos/kokkos-src/core/src/OpenMP',
        '-I/home/luca/workdir/kokkos/kokkos-src/core/src/Qthread',
        '-I/home/luca/workdir/kokkos/kokkos-src/core/src/Threads',
        '-I/home/luca/workdir/kokkos/kokkos-src/core/src/impl',
        '-I/home/luca/workdir/kokkos/kokkos-src/containers/src',
        '-I/home/luca/workdir/kokkos/kokkos-src/containers/src/impl',
        '-I/home/luca/workdir/kokkos/kokkos-src/algorithms/src',
]

IBECS_FLAGS = [
        '-I/home/luca/workdir/ibecs/ibecs-src/src/',
        '-I/home/luca/workdir/ibecs/ibecs-build-debug/src',
]

ALBANY_FLAGS = [
        '-I/home/luca/workdir/albany/albany-src/branch/src',
        '-I/home/luca/workdir/albany/albany-src/branch/src/adapt',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc/catalyst',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc/pumi',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc/stk',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc/stk/percept',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc/stk/percept/stk_rebalance',
        '-I/home/luca/workdir/albany/albany-src/branch/src/disc/stk/percept/stk_rebalance_utils',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/bc',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/gather',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/interpolation',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/pde',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/response',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/scatter',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/state',
        '-I/home/luca/workdir/albany/albany-src/branch/src/evaluators/utility',
        '-I/home/luca/workdir/albany/albany-src/branch/src/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/utility',
        '-I/home/luca/workdir/albany/albany-src/branch/src/utility/math',
        '-I/home/luca/workdir/albany/albany-src/branch/src/adapt',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Aeras',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Aeras/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Aeras/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Aeras/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/AFRL/communicators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/AFRL/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/AFRL/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/AMP/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/AMP/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/AMP/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/ANISO',
        '-I/home/luca/workdir/albany/albany-src/branch/src/ATO',
        '-I/home/luca/workdir/albany/albany-src/branch/src/ATO/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/ATO/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/ATO/utils',
        '-I/home/luca/workdir/albany/albany-src/branch/src/CTM',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LandIce',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LandIce/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LandIce/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LandIce/interface_with_cism',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LandIce/interface_with_mpas',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Hydride/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Hydride/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/bc',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/HMC',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/kinematics',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/lame',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/linear-elasticity',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/peridigm',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/poro',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/projection',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/residuals',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/size-field',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/surface-element',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/evaluators/transport',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/models',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/models/core',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/models/variational',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/parallel_evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/parallel_models',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/problems/lame',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/solvers',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/test/unit_tests',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/test/utils',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/utils',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/utils/dtk_interp_and_error',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/utils/lame',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/utils/mortar',
        '-I/home/luca/workdir/albany/albany-src/branch/src/LCM/utils/topology',
        '-I/home/luca/workdir/albany/albany-src/branch/src/MOR',
        '-I/home/luca/workdir/albany/albany-src/branch/src/QCAD',
        '-I/home/luca/workdir/albany/albany-src/branch/src/QCAD/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/QCAD/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/QCAD/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/responses',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Tsunami/evaluators',
        '-I/home/luca/workdir/albany/albany-src/branch/src/Tsunami/problems',
        '-I/home/luca/workdir/albany/albany-src/branch/src/utility',
        '-I/home/luca/workdir/albany/albany-build/gcc/opt/branch/src',
]

TRILINOS_FLAGS = [
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/aztecoo/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/belos/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/epetra/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/epetraext/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/epetraext/src/inout',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/epetraext/src/model_evaluator',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/epetraext/src/transform',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ifpack2/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/intrepid2/core/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/intrepid2/core/src/Cell',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/intrepid2/core/src/Discretization',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/intrepid2/core/src/Kokkos',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/intrepid2/core/src/Orientation',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/intrepid2/core/src/luca',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/kokkos/core/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/kokkos/containers/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/kokkos/algorithms/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Coarsen',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Comm',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/FEGrid',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Include',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Krylov',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/LevelWrap',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/MLAPI',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Main',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/MatrixFree',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Operator',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/RefMaxwell',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Smoother',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/ml/src/Utils',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Graph',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Headers',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Interface',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Misc',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/MueCentral',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Rebalancing',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Smoothers',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Transfers',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/muelu/src/Utils',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-loca/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-loca/src-epetra',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-loca/src-lapack',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-loca/src-mf',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-belos',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-petsc',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-thyra',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-epetra',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/nox/src-lapack',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/phalanx/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/piro/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rythmos/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/algorithm',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/elementwise',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/function',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/sol',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/status',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/step',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/utils',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/vector',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/rol/src/zoo',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/Fad/Fad',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/Fad/TinyFad',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/Fad/TinyFadET',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/Fad/utils',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/src/',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/src/mpl',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/src/parameter',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/sacado/src/template',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/stk/stk_io/stk_io',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/stk/stk_mesh/stk_mesh/base',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/stk/stk_mesh/stk_mesh/baseImpl',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/stk/stk_topology/stk_topology',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/stk/stk_util/stk_util',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/teuchos/core/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/teuchos/comm/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/teuchos/parameterlist/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/teuchos/numerics/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/teuchos/kokkoscompat/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/operator_vector/fundamental',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/operator_vector/extended',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/operator_solve/fundamental',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/operator_solve/extended',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/nonlinear/solvers/fundamental',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/nonlinear/solvers/extended',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/support/operator_vector/client_support',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/support/operator_vector/adapter_support',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/support/operator_solve/client_support',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/support/nonlinear/solvers/client_support',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/core/src/support/nonlinear/model_evaluator/client_support',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/adapters/epetra/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/adapters/epetraext/src/model_evaluator',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/adapters/epetraext/src/transformer',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/thyra/adapters/tpetra/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/tpetra/core/src',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/tpetra/core/inout',
        '-I/home/luca/workdir/trilinos/trilinos-src/packages/tpetra/core/ext',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include',
]

TRILINOS_INCLUDE_FLAGS = [
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/Cuda',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/generated_specializations_hpp',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/gtest',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/impl',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/OpenMP',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/Qthreads',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_expreval',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_io',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_math',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_mesh',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_ngp',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_search',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_simd',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_simd_view',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_tools',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_topology',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_transfer',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_unit_test_utils',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/stk_utils',
        '-isystem',
        '/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop/include/Threads',
]

KOKKOS_INCLUDE_FLAGS = [
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/Cuda',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/eti',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/impl',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/OpenMP',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/OpenMPTarget',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/Qthreads',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/ROCm',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/Serial',
        '-isystem',
        '/home/luca/workdir/kokkos/kokkos-install/marzemino/gcc/debug/include/Threads',
]

def in_directory(file, directory, allow_symlink = False):
    #make both absolute
    directory = os.path.realpath(directory)
    file = os.path.realpath(file)

    #check whether file is a symbolic link, if yes, return false if they are not allowed
    if not allow_symlink and os.path.islink(file):
        return False

    #return true, if the common prefix of both is equal to directory
    #e.g. /a/b/c/d.rst and directory is /a/b, the common prefix is /a/b
    return os.path.commonprefix([file, directory]) == directory

def FlagsForFile(filename, **kwargs):
    final_flags = []
    is_scream = in_directory(filename,'/home/luca/workdir/scream/scream-src')
    if is_scream :
      final_flags = final_flags + SCREAM_FLAGS + KOKKOS_INCLUDE_FLAGS
    is_e3sm = in_directory(filename,'/home/luca/workdir/e3sm/e3sm-src')
    if is_e3sm :
      final_flags = final_flags + E3SM_FLAGS + KOKKOS_INCLUDE_FLAGS
    is_homme = in_directory(filename,'/home/luca/workdir/hommexx/hommexx-src')
    if is_homme :
      final_flags = final_flags + HOMME_FLAGS + KOKKOS_INCLUDE_FLAGS
    is_kokkos = in_directory(filename,'/home/luca/workdir/kokkos/kokkos-src')
    if is_kokkos :
      final_flags = final_flags + KOKKOS_FLAGS
    is_albany = in_directory(filename,'/home/luca/workdir/albany/albany-src')
    if is_albany:
      final_flags = final_flags + ALBANY_FLAGS + TRILINOS_INCLUDE_FLAGS
    is_ibecs = in_directory(filename,'/home/luca/workdir/ibecs/ibecs-src')
    if is_ibecs :
      final_flags = final_flags + IBECS_FLAGS + TRILINOS_INCLUDE_FLAGS
    is_trilinos = in_directory(filename,'/home/luca/workdir/trilinos/trilinos-src')
    if is_trilinos :
      final_flags = final_flags + TRILINOS_FLAGS

    final_flags = final_flags + BASE_FLAGS;

    return {
      'flags'    : final_flags,
    }
